finished rest tasks from module 1
js-tasks-ru/jsbasic-20210621_jouway pull request #2
Opened 2021-06-28 19:44 UTC by irogozhova

2021-06-28 19:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-29 20:39 UTC, SinimaWath requested changes

2021-06-29 20:39 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return name !== '' && name.indexOf(' ') === -1 && name.length >= 4;
Давай заменим indexOf, на более простой метод includes

2021-06-29 20:39 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
Тут можно написать без else, так как в if условии ты все равно выходишь из функции

2021-06-30 09:01 UTC, irogozhova commented on 1-module/2-task/index.js
> +  return name !== '' && name.indexOf(' ') === -1 && name.length >= 4;
Согласна, спс

2021-06-30 09:01 UTC, irogozhova commented on 1-module/5-task/index.js
> +  }
Согласна, спасибо

2021-06-30 09:13 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 15:19 UTC, SinimaWath approved these changes

2021-07-01 15:20 UTC, merged